# Generated by Django 4.2 on 2024-05-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_student_qr_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="name",
        ),
        migrations.AddField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="teacher",
            name="practioner_license",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="teacher",
            name="teaching_grade",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="teacher",
            name="teaching_subject",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
