# Generated by Django 4.2 on 2024-05-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_remove_teacher_name_teacher_first_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Teacher",
            new_name="Staff",
        ),
    ]
