# Generated by Django 4.2 on 2024-05-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_rename_teacher_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="unique_id",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="unique_id",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
    ]
