# Generated by Django 4.2 on 2024-05-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_staff_unique_id_student_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="staff_qrcodes/"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="unique_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="unique_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
