# Generated by Django 4.2 on 2024-05-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0007_alter_student_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="unique_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
