# Generated by Django 4.2 on 2024-05-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0008_alter_student_unique_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="qr_code",
        ),
        migrations.AlterField(
            model_name="staff",
            name="unique_id",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
    ]
