# Generated by Django 4.2 on 2024-05-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0009_remove_staff_qr_code_alter_staff_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="contact",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="staff",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="staff_qrcodes/"),
        ),
    ]
