# Generated by Django 4.2 on 2024-05-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0011_alter_staff_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
            ),
        ),
    ]
