# Generated by Django 4.2 on 2024-05-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0012_alter_student_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
